package sasa;

import sasa.commands.Command;
import sasa.exception.SasaException;
import sasa.parser.Parser;
import sasa.storage.Storage;
import sasa.tasks.TaskList;
import sasa.ui.Ui;

/**
 * Main class for the sasa.Sasa chatbot
 * Sasa is a task management assistant that allows users to track todos, deadlines and events.
 * It handles the initialization of core components and manages the main execution loop.
 */
public class Sasa {
    private final Ui ui;
    private final Storage storage;
    private TaskList tasks;
    private String commandType;

    /**
     * Constructs a Sasa instance and initializes the UI, Storage and TaskList.
     * Loads existing tasks from the specified file path.
     *
     * @param filePath The path to the file where task data is stored.
     */
    public Sasa(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        this.tasks = initializeTaskList();
    }

    private TaskList initializeTaskList() {
        try {
            return new TaskList(storage.load());
        } catch (SasaException e) {
            ui.showLoadingError();
            return new TaskList();
        }
    }

    /**
     * Main entry point for the application.
     *
     * @param args sasa.commands.Command line arguments.
     */
    public static void main(String[] args) {
        new Sasa("data/sasa.txt").run();
    }

    /**
     * Starts the main execution loop of the chatbot.
     * The loop continues to read and execute user commands until an exit command is received.
     */
    public void run() {
        ui.showWelcome();
        boolean isExit = false;

        while (!isExit) {
            try {
                String fullCommand = ui.readCommand();
                ui.showLine();
                Command c = Parser.parse(fullCommand);
                c.execute(tasks, ui, storage);
                isExit = c.isExit();
            } catch (SasaException e) {
                ui.showError(e.getMessage());
            } finally {
                ui.showLine();
            }
        }
    }

    /**
     * Processes a single user input string and returns the chatbot's response.
     *
     * @param input The raw text input from the user.
     * @return The response string generated by the executed command.
     */
    public String getResponse(String input) {
        try {
            Command c = Parser.parse(input);
            c.execute(tasks, ui, storage);
            commandType = c.getClass().getSimpleName();
            return c.getReply();
        } catch (SasaException e) {
            return e.getMessage();
        }
    }

    /**
     * Retrieves the simple class name of the last executed command.
     *
     * @return The simple name of the command class (e.g., "AddCommand").
     */
    public String getCommandType() {
        return commandType;
    }
}
